services:
  collector:
    build:
      context: .
    image: terra-uc1-collector:local
    env_file:
      - .env
    environment:
      CDSE_CLIENT_ID: ${CDSE_CLIENT_ID:-}
      CDSE_CLIENT_SECRET: ${CDSE_CLIENT_SECRET:-}
      CDSE_BACKUP_CLIENT_ID: ${CDSE_BACKUP_CLIENT_ID:-}
      CDSE_BACKUP_CLIENT_SECRET: ${CDSE_BACKUP_CLIENT_SECRET:-}
      CDSE_BACKUP_2_CLIENT_ID: ${CDSE_BACKUP_2_CLIENT_ID:-}
      CDSE_BACKUP_2_CLIENT_SECRET: ${CDSE_BACKUP_2_CLIENT_SECRET:-}
      CDSE_BACKUP_3_CLIENT_ID: ${CDSE_BACKUP_3_CLIENT_ID:-}
      CDSE_BACKUP_3_CLIENT_SECRET: ${CDSE_BACKUP_3_CLIENT_SECRET:-}
      CDSE_BACKUP_4_CLIENT_ID: ${CDSE_BACKUP_4_CLIENT_ID:-}
      CDSE_BACKUP_4_CLIENT_SECRET: ${CDSE_BACKUP_4_CLIENT_SECRET:-}
      CDSE_BACKUP_5_CLIENT_ID: ${CDSE_BACKUP_5_CLIENT_ID:-}
      CDSE_BACKUP_5_CLIENT_SECRET: ${CDSE_BACKUP_5_CLIENT_SECRET:-}
      CDSE_BACKUP_6_CLIENT_ID: ${CDSE_BACKUP_6_CLIENT_ID:-}
      CDSE_BACKUP_6_CLIENT_SECRET: ${CDSE_BACKUP_6_CLIENT_SECRET:-}
      CDSE_BACKUP_7_CLIENT_ID: ${CDSE_BACKUP_7_CLIENT_ID:-}
      CDSE_BACKUP_7_CLIENT_SECRET: ${CDSE_BACKUP_7_CLIENT_SECRET:-}
      CDSE_BACKUP_8_CLIENT_ID: ${CDSE_BACKUP_8_CLIENT_ID:-}
      CDSE_BACKUP_8_CLIENT_SECRET: ${CDSE_BACKUP_8_CLIENT_SECRET:-}
      CDSE_BACKUP_9_CLIENT_ID: ${CDSE_BACKUP_9_CLIENT_ID:-}
      CDSE_BACKUP_9_CLIENT_SECRET: ${CDSE_BACKUP_9_CLIENT_SECRET:-}
      TERRA_AOI_ID: ${TERRA_AOI_ID:-}
      MONGO_URI: ${MONGO_URI:-}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT:-}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME:-}
      MINIO_VERIFY_TLS: ${MINIO_VERIFY_TLS:-true}
      MINIO_CA_BUNDLE: ${MINIO_CA_BUNDLE:-}
    volumes:
      - ./outputs:/app/outputs
    init: true
